spring.application.name=airbnb
server.port=3501
spring.datasource.url=jdbc:postgresql://localhost:5432/airbnb
spring.datasource.username=pac_user
spring.datasource.password=pac_user
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.servlet.context-path=/api/v1

jwt.secretKey=sdhfjeqbskhjfabvekjqwirj239pewfjcjnbnvknecqmdncmsnjbdcjhdsbcvkjnkjsdcnjkkedkcvnkd

frontend.url=http://localhost:3501
stripe.api.key=<Update_your_Key>
stripe.webhook.secret=whsec_0b29d1ca8c9fcf672c805ad2b1b3cb9905f2ecb2268a0a31adc5621642e1f5bd